name: Notify Slack

on:
  workflow_run:
    workflows: ["API Tests"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub Pages to deploy
        run: |
          echo "⏳ Waiting for GitHub Pages to finish deploying..."
          for i in {1..30}; do
            status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/htuanln97/java-api-test/pages/builds/latest | jq -r .status)
            echo "GitHub Pages status: $status"
            if [ "$status" = "built" ]; then
              echo "✅ Pages deployed!"
              break
            fi
            sleep 5
          done

      - name: Notify Slack
        id: get_report
        if: always()
        run: |
          STATUS=${{ job.status }}
          curl -X POST -H 'Content-type: application/json' \
          --data "{
          \"text\": \":robot_face: API Tests *$STATUS* — Report: https://htuanln97.github.io/java-api-test/$latest_report_id/\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
