name: API Tests

on:
  push:          # chạy khi push code
    branches:
      - main     # hoặc branch bạn muốn (develop, master, …)
  workflow_dispatch:   # cho phép chạy tay luôn
  schedule:
    - cron: "0 2 * * *" # vẫn giữ schedule chạy 9h sáng VN hằng ngày

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the Project
        run: mvn clean install -DskipTests=true

      - name: Run API tests with Maven
        run: mvn test

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Archive Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
