name: API Tests

on:
  push:          # chạy khi push code
    branches:
      - main     # hoặc branch bạn muốn (develop, master, …)
  workflow_dispatch:   # cho phép chạy tay luôn
  schedule:
    - cron: "0 2 * * *" # vẫn giữ schedule chạy 9h sáng VN hằng ngày

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the Project
        run: mvn clean install -DskipTests=true

      - name: Run API tests with Maven
        run: mvn test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report-depoyment
          path: report-depoyment

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: report-depoyment
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-depoyment
          publish_dir: allure-history
